# Generated by Django 5.0.3 on 2024-03-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_client', models.CharField(max_length=60)),
                ('phone', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, null=True)),
                ('city', models.CharField(blank=True, null=True)),
                ('street', models.CharField(blank=True, null=True)),
                ('house', models.CharField(blank=True, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('mail', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'barbershop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('surname', models.CharField()),
                ('phone', models.BigIntegerField(unique=True)),
                ('mail', models.CharField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('surname', models.CharField()),
                ('patronymic', models.CharField(blank=True, null=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('mail', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'master_service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(unique=True)),
            ],
            options={
                'db_table': 'position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='corp.staff')),
                ('passport', models.BigIntegerField(unique=True)),
                ('employment_record_number', models.BigIntegerField(unique=True)),
                ('snils', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
    ]
